apiVersion: v1
kind: Pod
metadata:
  name: prime-service
spec:
  containers:
  - name: prime-container
    image: viviviri/prime-service:latest
    imagePullPolicy: Never
    command: ["./prime_service", "generate", "5"]
