apiVersion: v1
kind: Pod
metadata:
  name: prime-service
spec:
  containers:
  - name: prime-container
    image: prime-service
    imagePullPolicy: IfNotPresent
    command: ["./prime_service", "generate", "5"]
